-- MySQL Script generated by MySQL Workbench
-- Sun May 27 16:15:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MequipamentosODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Estoque
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Estoque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Estoque` DEFAULT CHARACTER SET utf8 ;
USE `Estoque` ;

-- -----------------------------------------------------
-- Table `Estoque`.`equipamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Estoque`.`equipamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fabricante` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `veiculo` VARCHAR(45) NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Estoque`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Estoque`.`pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `endereço` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `equipamentos_id` INT NOT NULL,
  PRIMARY KEY (`id`, `equipamentos_id`),
  INDEX `fk_pedidos_equipamentos_idx` (`equipamentos_id` ASC),
  CONSTRAINT `fk_pedidos_equipamentos`
    FOREIGN KEY (`equipamentos_id`)
    REFERENCES `Estoque`.`equipamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Estoque`.`trocas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Estoque`.`trocas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NULL,
  `nome_cliente` VARCHAR(45) NULL,
  `modelo_veiculo` VARCHAR(45) NULL,
  `ano_veiculo` VARCHAR(45) NULL,
  `placa_veiculo` VARCHAR(45) NULL,
  `atividade` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
