insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Scion', 2005, 'xB', 6);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mercedes-Benz', 2003, 'E-Class', 10);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Toyota', 2003, 'Sienna', 1);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Lexus', 2004, 'SC', 16);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 2012, 'Traverse', 20);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Subaru', 1986, 'Leone', 12);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Dodge', 1998, 'Durango', 17);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mercury', 1968, 'Cougar', 19);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Lamborghini', 1998, 'Diablo', 6);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ford', 1986, 'E-Series', 3);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ferrari', 2012, '458 Italia', 3);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Toyota', 2003, 'Land Cruiser', 13);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mitsubishi', 1994, 'Diamante', 3);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chrysler', 2001, 'Town & Country', 2);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Dodge', 2011, 'Journey', 14);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mercury', 1986, 'Grand Marquis', 14);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Porsche', 1986, '944', 7);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Oldsmobile', 2000, 'Alero', 19);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Cadillac', 2006, 'Escalade EXT', 16);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Honda', 1993, 'del Sol', 12);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Cadillac', 2011, 'STS', 4);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ford', 1999, 'F350', 4);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ford', 1998, 'Econoline E150', 7);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Nissan', 2011, 'Sentra', 10);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Dodge', 2010, 'Caravan', 18);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Audi', 1990, 'Coupe Quattro', 3);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Dodge', 2008, 'Nitro', 13);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('BMW', 2006, 'Z4 M', 12);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Nissan', 2012, 'Rogue', 19);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mazda', 2011, 'Mazda2', 5);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Oldsmobile', 1999, 'LSS', 4);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Land Rover', 2006, 'Discovery', 14);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 2009, 'Malibu', 16);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mercedes-Benz', 1985, 'SL-Class', 4);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('BMW', 2004, '525', 4);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mitsubishi', 2005, 'Eclipse', 3);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mercedes-Benz', 1998, 'CL-Class', 16);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('MINI', 2007, 'Cooper', 5);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Nissan', 2004, 'Frontier', 12);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('GMC', 2008, 'Sierra', 6);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('GMC', 2004, 'Savana 3500', 3);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Volkswagen', 2012, 'Eos', 18);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Toyota', 1998, 'RAV4', 15);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Pontiac', 1984, 'Fiero', 4);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ford', 1998, 'Ranger', 14);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mercedes-Benz', 2005, 'SL-Class', 6);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Acura', 2001, 'MDX', 18);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Jeep', 2004, 'Wrangler', 2);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mercedes-Benz', 1988, 'S-Class', 14);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Saturn', 2007, 'Ion', 4);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Pontiac', 2005, 'Montana SV6', 8);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Kia', 2004, 'Spectra', 6);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Infiniti', 1994, 'J', 8);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Nissan', 2010, 'Maxima', 3);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Dodge', 2000, 'Stratus', 1);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Toyota', 1993, 'Corolla', 2);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Audi', 2008, 'S5', 12);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mitsubishi', 2006, 'Montero', 9);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Lincoln', 1999, 'Navigator', 14);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Honda', 2011, 'Ridgeline', 10);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ford', 2008, 'F350', 3);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Volvo', 2009, 'C30', 16);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Jeep', 1999, 'Cherokee', 7);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mercedes-Benz', 2007, 'CL-Class', 15);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Porsche', 2001, 'Boxster', 12);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Toyota', 2007, 'Matrix', 14);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('BMW', 2001, '3 Series', 13);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('BMW', 2009, '6 Series', 19);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Dodge', 2009, 'Nitro', 19);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Buick', 1997, 'Century', 11);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Dodge', 2008, 'Nitro', 19);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mercedes-Benz', 1986, 'S-Class', 16);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Cadillac', 2007, 'Escalade EXT', 10);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chrysler', 2008, 'Pacifica', 10);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 1967, 'Camaro', 9);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mazda', 1999, 'Millenia', 14);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ford', 1997, 'Escort', 6);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Volkswagen', 2008, 'New Beetle', 18);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Isuzu', 1995, 'Trooper', 16);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('GMC', 2004, 'Sierra 2500', 11);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 1976, 'Camaro', 13);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Buick', 2003, 'Park Avenue', 2);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Lincoln', 1991, 'Continental', 4);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 1968, 'Corvette', 16);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Toyota', 2010, 'Sienna', 19);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ford', 2011, 'Transit Connect', 4);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Jaguar', 2003, 'X-Type', 2);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Audi', 2010, 'S4', 4);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ford', 1990, 'LTD Crown Victoria', 14);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Hyundai', 2010, 'Genesis Coupe', 7);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 1994, 'Beretta', 16);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Dodge', 1997, 'Dakota', 19);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Volvo', 1999, 'S70', 9);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Infiniti', 2002, 'G', 17);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mercedes-Benz', 2000, 'SLK-Class', 13);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mazda', 1988, '626', 16);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mazda', 1992, 'RX-7', 6);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chrysler', 2005, '300', 9);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Nissan', 1995, '240SX', 9);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 2011, 'Express 3500', 12);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Infiniti', 1993, 'J', 14);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 1999, 'Express 1500', 14);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Porsche', 1994, '968', 19);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('GMC', 2010, 'Yukon XL 1500', 18);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mercury', 1997, 'Mystique', 10);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('GMC', 1998, 'Yukon', 10);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 2010, 'Express', 7);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Plymouth', 1997, 'Grand Voyager', 13);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Lincoln', 2001, 'LS', 19);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Volvo', 2007, 'S40', 3);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Kia', 2008, 'Optima', 8);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Volkswagen', 1990, 'Type 2', 17);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('GMC', 2008, 'Acadia', 5);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mitsubishi', 1984, 'Cordia', 15);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Saturn', 2003, 'Ion', 8);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Nissan', 2011, 'GT-R', 11);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Lexus', 2011, 'ES', 17);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Cadillac', 2003, 'Seville', 11);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Lincoln', 1985, 'Continental', 12);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Toyota', 2010, 'Tacoma', 17);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Infiniti', 2003, 'QX', 16);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Lexus', 2007, 'SC', 14);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mercedes-Benz', 2012, 'SLS-Class', 20);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Infiniti', 2012, 'G', 1);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('MINI', 2012, 'Cooper Countryman', 13);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mazda', 2003, 'B-Series Plus', 11);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 2001, 'Silverado 3500', 11);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Volvo', 2010, 'XC70', 8);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Honda', 1999, 'CR-V', 8);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Hyundai', 2008, 'Entourage', 7);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Saab', 2010, '9-3', 2);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Lincoln', 2011, 'Town Car', 11);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 1995, 'G-Series G30', 7);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mazda', 2003, 'B-Series', 20);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ford', 2006, 'E350', 15);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Jeep', 1995, 'Grand Cherokee', 8);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Jaguar', 2003, 'XJ Series', 1);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Lincoln', 1988, 'Continental', 16);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mercury', 1985, 'Topaz', 13);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Isuzu', 2005, 'Ascender', 13);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Acura', 1992, 'Legend', 17);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mercedes-Benz', 2007, 'CL-Class', 13);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mercury', 2000, 'Villager', 5);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Pontiac', 1998, 'Grand Prix', 19);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Pontiac', 2002, 'Grand Am', 3);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Hyundai', 2002, 'XG350', 18);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Acura', 2011, 'TSX', 10);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Suzuki', 2006, 'Verona', 14);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Volvo', 2009, 'S60', 19);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mercedes-Benz', 2003, 'C-Class', 14);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Oldsmobile', 1992, '98', 2);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Kia', 2005, 'Sorento', 11);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Porsche', 1995, '928', 2);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Bentley', 2006, 'Continental Flying Spur', 4);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Infiniti', 2009, 'EX', 15);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Suzuki', 2004, 'Swift', 19);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Volkswagen', 2002, 'rio', 14);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Isuzu', 2006, 'i-280', 7);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Cadillac', 1999, 'Seville', 5);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Audi', 2001, 'TT', 6);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chrysler', 1999, 'Sebring', 19);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 2011, 'Impala', 14);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Infiniti', 2006, 'G', 18);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 2005, 'Suburban 1500', 4);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Honda', 2011, 'Pilot', 14);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mercury', 1984, 'Cougar', 14);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Dodge', 2012, 'Caravan', 11);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('GMC', 1999, 'Sierra 1500', 11);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mitsubishi', 1988, 'L300', 4);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Pontiac', 1996, 'Grand Prix', 12);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Suzuki', 1989, 'SJ', 13);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chrysler', 2008, 'Pacifica', 16);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Hyundai', 2004, 'Elantra', 5);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mitsubishi', 2004, 'Lancer', 19);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 2000, 'Camaro', 16);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Cadillac', 1993, 'Sixty Special', 20);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ford', 2001, 'Econoline E350', 19);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Honda', 2006, 'Insight', 10);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Subaru', 1991, 'Legacy', 20);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ford', 1986, 'E-Series', 4);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Kia', 2006, 'Spectra', 16);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mercedes-Benz', 2005, 'M-Class', 10);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chrysler', 1998, 'Sebring', 3);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Nissan', 2000, 'Frontier', 2);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ford', 1984, 'E250', 13);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Lexus', 1996, 'ES', 5);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chrysler', 2009, 'PT Cruiser', 3);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Pontiac', 1967, 'Tempest', 9);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('BMW', 2011, 'Z4', 17);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 1996, 'Suburban 1500', 10);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 1999, 'Suburban 2500', 14);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mercedes-Benz', 1996, 'S-Class', 2);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 2009, 'TrailBlazer', 8);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Dodge', 1993, 'Ramcharger', 12);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 2000, 'Malibu', 19);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Toyota', 1995, 'T100', 6);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Lexus', 2003, 'ES', 16);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mitsubishi', 1993, 'Mighty Max', 8);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Suzuki', 2002, 'XL-7', 15);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chrysler', 1996, 'Town & Country', 7);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Land Rover', 2011, 'Range Rover Sport', 11);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Honda', 2007, 'Accord', 18);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Toyota', 2007, 'Camry Hybrid', 9);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Lexus', 1999, 'SC', 7);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ford', 1986, 'Taurus', 4);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mercedes-Benz', 2008, 'R-Class', 3);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Pontiac', 2007, 'G6', 18);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mitsubishi', 1985, 'Mirage', 15);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Toyota', 1998, 'Land Cruiser', 16);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Suzuki', 2010, 'SX4', 6);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 2011, 'Corvette', 10);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mercedes-Benz', 2011, 'E-Class', 12);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 2005, 'Uplander', 12);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Tesla', 2012, 'Roadster', 2);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Dodge', 2001, 'Ram Van 1500', 14);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Isuzu', 1997, 'Rodeo', 17);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ford', 2008, 'Taurus', 10);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Oldsmobile', 1966, 'Toronado', 15);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 1979, 'Camaro', 7);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ford', 1988, 'Taurus', 11);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Acura', 2005, 'RL', 12);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Pontiac', 1992, 'Firefly', 18);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Subaru', 1990, 'Loyale', 2);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Kia', 2008, 'Spectra', 11);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 2008, 'Corvette', 15);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Isuzu', 2000, 'Hombre', 8);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Hyundai', 2007, 'Accent', 11);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ford', 2008, 'F-Series Super Duty', 20);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Toyota', 1982, 'Celica', 3);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 1995, '1500', 13);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ford', 1972, 'Thunderbird', 12);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Maybach', 2012, 'Landaulet', 6);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Pontiac', 2005, 'GTO', 4);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ferrari', 2010, 'California', 13);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ford', 2010, 'F250', 6);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Dodge', 2003, 'Ram Van 3500', 8);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Acura', 2001, 'CL', 4);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Oldsmobile', 1995, 'Cutlass Supreme', 15);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Toyota', 2004, 'Corolla', 1);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 1997, 'Corvette', 12);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Audi', 1990, '100', 7);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Pontiac', 1986, 'Grand Prix', 19);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mitsubishi', 2005, 'Eclipse', 10);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 2005, 'Avalanche 2500', 17);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('MG', 1977, 'MGB', 9);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 2001, 'Suburban 1500', 16);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Pontiac', 2005, 'Grand Prix', 4);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Kia', 2010, 'Forte', 7);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 2007, 'Malibu', 3);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Foose', 2007, 'Hemisfear', 1);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Honda', 2010, 'CR-V', 17);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Infiniti', 1995, 'J', 20);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Lexus', 2006, 'ES', 3);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ford', 2001, 'Mustang', 20);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Subaru', 2002, 'Legacy', 10);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Jeep', 2010, 'Wrangler', 6);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ford', 2012, 'F150', 1);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Jeep', 1993, 'Grand Cherokee', 13);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mitsubishi', 1990, 'Galant', 14);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Subaru', 2010, 'Legacy', 10);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Dodge', 1992, 'D250 Club', 14);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Pontiac', 2002, 'Firebird', 19);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Toyota', 2012, 'RAV4', 8);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ford', 1988, 'Escort', 11);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mazda', 1996, 'Miata MX-5', 3);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Honda', 2012, 'Fit', 10);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mitsubishi', 2006, 'Lancer Evolution', 16);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('BMW', 1959, '600', 13);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Suzuki', 1988, 'SJ', 16);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mitsubishi', 2009, 'Raider', 20);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Honda', 2008, 'Odyssey', 3);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Saturn', 2000, 'L-Series', 12);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mazda', 1996, 'B-Series Plus', 17);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Buick', 2004, 'Park Avenue', 10);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('GMC', 1995, 'Vandura G3500', 2);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Cadillac', 2012, 'Escalade', 13);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Subaru', 1996, 'SVX', 3);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Volkswagen', 2006, 'Jetta', 6);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Chevrolet', 2010, 'HHR', 15);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('GMC', 2005, 'Yukon XL 1500', 19);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mitsubishi', 1997, 'Eclipse', 20);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('BMW', 2006, '760', 1);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Eagle', 1996, 'Vision', 10);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Volvo', 2009, 'V50', 4);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Pontiac', 1990, 'Firefly', 6);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Honda', 2000, 'S2000', 16);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Lexus', 2012, 'LS', 7);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Saab', 1998, '9000', 8);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Lexus', 1998, 'LX', 6);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Jaguar', 2007, 'XK', 2);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Aston Martin', 2007, 'DB9', 10);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Pontiac', 1991, '6000', 14);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Mercedes-Benz', 2008, 'CLK-Class', 19);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Pontiac', 1999, 'Grand Am', 16);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ford', 1996, 'Crown Victoria', 19);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Volkswagen', 1993, 'Golf', 16);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Aston Martin', 2009, 'V8 Vantage', 18);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Maserati', 1990, 'Karif', 9);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Ford', 2001, 'Explorer Sport Trac', 10);
insert into equipamentos (fabricante, modelo, veiculo, quantidade) values ('Plymouth', 1964, 'Fury', 11);
